import Link from "next/link";
import { Check, Minus } from "lucide-react";
import PricingCards from "@/components/marketing/PricingCards";
import Reveal from "@/components/marketing/Reveal";

const comparison = [
  ["Staff accounts", "5", "10", "25"], ["Customers", "200", "750", "2,500"], ["Orders/month", "1,000", "3,000", "10,000"], ["Products", "50", "150", "500"], ["AI queries/month", "50", "500", "2,000"], ["SMS/month included", "100", "500", "1,500"], ["Autopilot actions/month", "0", "100", "1,000"],
  ["War Room", true, true, true], ["Order Pipeline", true, true, true], ["Payment Verification", true, true, true], ["OTP Delivery", true, true, true], ["Company Brain", true, true, true], ["Incoming Stock", true, true, true], ["Store Pickup", true, true, true],
  ["Tasks", false, true, true], ["Autopilot", false, "Limited", true], ["SMS Broadcasts", false, true, true], ["Performance Tracking", false, true, true], ["Activity Log", false, true, true], ["Association Dashboard", false, false, true], ["Support", "Email", "WhatsApp", "Priority"],
];
function Cell({ value }: { value: string | boolean }) { return <span className="inline-flex min-h-8 items-center justify-center">{value === true ? <Check size={17} className="text-green" strokeWidth={3} /> : value === false ? <Minus size={16} className="text-ink3" /> : value}</span>; }

export default function PricingPage() {
  return <><section className="bg-blue-pale py-20 text-center sm:py-24"><Reveal><div className="mx-auto max-w-3xl px-5 sm:px-8"><p className="font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-blue-primary">Simple, transparent pricing</p><h1 className="mt-4 font-display text-5xl font-bold leading-tight text-ink sm:text-6xl">Simple pricing for every stage of your business.</h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-ink2">Start with a 14-day free trial. No credit card required, and no surprises when your team grows.</p></div></Reveal></section><section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><PricingCards /></Reveal><Reveal className="mt-20"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-blue-primary">Full comparison</p><h2 className="mt-3 font-display text-4xl font-bold text-ink">Choose the room you need to grow.</h2></div><Link href="/signup" className="text-sm font-bold text-blue-primary hover:underline">Start your free trial</Link></div><div className="mt-8 overflow-x-auto rounded-xl border border-blue-border"><div className="min-w-[680px]"><div className="grid grid-cols-[1.6fr_1fr_1fr_1fr] bg-blue-pale px-5 py-4 text-sm font-bold text-ink"><span>Feature</span><span className="text-center">Starter</span><span className="text-center text-blue-primary">Growth</span><span className="text-center">Professional</span></div>{comparison.map(([feature, starter, growth, professional]) => <div key={String(feature)} className="grid grid-cols-[1.6fr_1fr_1fr_1fr] border-t border-blue-border px-5 py-3 text-sm text-ink2"><span className="font-medium text-ink">{feature}</span><Cell value={starter as string | boolean} /><Cell value={growth as string | boolean} /><Cell value={professional as string | boolean} /></div>)}</div></div></Reveal></div></section></>;
}
