"use client";

import Link from "next/link";
import { ArrowRight, Check, ChevronDown, ChevronUp } from "lucide-react";
import { useState } from "react";
import DashboardPreview from "@/components/marketing/DashboardPreview";
import PricingCards from "@/components/marketing/PricingCards";
import Reveal from "@/components/marketing/Reveal";

const pains = [
  ["📱", "Orders in 6 different WhatsApp groups", "You’ve got a group for walk-ins, one for Instagram DMs, one for phone orders. Something always gets lost."],
  ["💸", "Same payment proof. Two different orders.", "A customer sends one receipt to two reps. Both confirm it. You’ve shipped twice but been paid once."],
  ["🚚", "Did the rider actually deliver it?", "Your rider says delivered. The customer says they never received it. You have no proof either way."],
];
const features = [
  ["⚡", "War Room", "See today’s revenue, orders, and outstanding payments the moment you log in."],
  ["👥", "Customer Intelligence", "Every buyer’s history, health score, and lifetime value - know who to call before they go silent."],
  ["📦", "Order Pipeline", "WhatsApp, walk-in, Instagram, phone - all your orders in one pipeline from quote to delivered."],
  ["💳", "Payment Verification", "Anti-fraud receipt hashing means the same proof can never confirm two orders. Ever."],
  ["🚚", "OTP Delivery Confirmation", "Customers get a 6-digit code at dispatch. Riders must enter it to complete delivery. No fake deliveries."],
  ["🧠", "Company Brain", "Ask anything about your business in plain language. Pricing, processes, policies - answered instantly."],
  ["📊", "Performance Tracking", "See exactly what every team member has done - orders created, payments submitted, deliveries completed."],
  ["✨", "Autopilot", "Paste a WhatsApp conversation. Autopilot extracts the order, matches products, and builds a quote in seconds."],
  ["💼", "Payroll & HR", "Nigerian PAYE, pension, NHF, and leave management built right in. No separate payroll software needed."],
];
const industries = ["📱 Electronics & Gadgets", "👗 Fashion & Apparel", "💎 Jewelry & Accessories", "💄 Beauty & Cosmetics", "🛒 Retail & General Trade", "🍱 Food & Groceries", "🔧 Auto Parts", "📦 Any product business"];
const faqs = [
  ["Do I need a credit card to start?", "No. Your 14-day free trial starts the moment you sign up. No card required. You only pay when your trial ends and you choose a plan."],
  ["What happens to my data if I cancel?", "Your data is yours. You can export everything - customers, orders, products - as CSV at any time. If you cancel, we keep your data for 30 days so you can retrieve it."],
  ["Can I accept payments from customers?", "Yes. Connect your Paystack account in Settings and your customers can pay by card or bank transfer directly from their order tracking page. Don’t have Paystack? Bank transfer always works."],
  ["Do I need a website to use Cardinal OS?", "No. Cardinal OS Markets is your complete back-office system. Orders come in from WhatsApp, walk-in, phone, or Instagram - you record them in Cardinal. No website needed."],
  ["What if I already have a website?", "For now, you record website orders manually in Cardinal. Automatic website sync is available on our Enterprise plan for businesses with high website order volume."],
  ["Can I add my team members?", "Yes. Starter includes 5 staff accounts, Growth includes 10, and Professional includes 25. Each person gets a role-specific login - they only see what their job requires."],
];

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-blue-primary">{children}</p>; }
function Heading({ children }: { children: React.ReactNode }) { return <h2 className="mt-3 max-w-2xl font-display text-4xl font-bold leading-[1.05] text-ink sm:text-5xl">{children}</h2>; }

export default function HomePage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  return <>
    <section className="overflow-hidden bg-blue-pale"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 pb-16 pt-14 sm:px-8 lg:grid-cols-[0.94fr_1.06fr] lg:pb-24 lg:pt-20"><Reveal><div><span className="inline-flex items-center gap-2 rounded-full border border-blue-border bg-white px-3 py-1.5 font-mono text-[10px] font-bold uppercase tracking-[0.08em] text-blue-primary"><span className="h-2 w-2 rounded-full bg-green" />Live · Trusted by traders across Lagos</span><h1 className="mt-6 max-w-xl font-display text-5xl font-bold leading-[0.98] text-ink sm:text-6xl">Run your entire business from one place.</h1><p className="mt-6 max-w-xl text-base leading-7 text-ink2 sm:text-lg">Cardinal OS Markets helps traders in Lagos manage orders, payments, customers, and deliveries - without the WhatsApp chaos and spreadsheet headaches.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-blue-primary px-5 text-sm font-bold text-white shadow-sm transition hover:bg-blue-dark">Start Free Trial - 14 days free <ArrowRight size={17} /></Link><a href="#features" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-blue-border bg-white px-5 text-sm font-bold text-blue-primary transition hover:bg-blue-light">See how it works</a></div><div className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-xs font-semibold text-ink2"><span><Check className="mr-1 inline h-4 w-4 text-green" />No credit card required</span><span><Check className="mr-1 inline h-4 w-4 text-green" />Set up in 10 minutes</span><span><Check className="mr-1 inline h-4 w-4 text-green" />Cancel anytime</span></div></div></Reveal><Reveal className="lg:pl-5"><DashboardPreview /></Reveal></div></section>
    <div className="overflow-hidden bg-blue-primary py-3 text-white"><div className="marketing-marquee flex min-w-max gap-8 whitespace-nowrap font-mono text-[10px] font-bold uppercase tracking-[0.12em]"><span>Order Management · Customer Intelligence · OTP Delivery · Anti-Fraud Payments · Company Brain · SMS Broadcasts · Dispatch & Riders · Product Catalogue · Performance Tracking ·</span><span>Order Management · Customer Intelligence · OTP Delivery · Anti-Fraud Payments · Company Brain · SMS Broadcasts · Dispatch & Riders · Product Catalogue · Performance Tracking ·</span></div></div>
    <section className="bg-blue-pale py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><Eyebrow>Sound familiar?</Eyebrow><Heading>Every trader knows this feeling.</Heading></Reveal><div className="mt-10 grid gap-4 md:grid-cols-3">{pains.map(([icon, title, copy]) => <Reveal key={title}><article className="h-full rounded-xl border border-blue-border bg-white p-6"><span className="text-3xl">{icon}</span><h3 className="mt-5 font-display text-2xl font-bold leading-tight text-ink">{title}</h3><p className="mt-3 text-sm leading-6 text-ink2">{copy}</p></article></Reveal>)}</div></div></section>
    <section id="features" className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><Eyebrow>Cardinal OS Markets</Eyebrow><Heading>One system. Every part of your business.</Heading></Reveal><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([icon, title, copy]) => <Reveal key={title}><article className="h-full rounded-xl border border-blue-border bg-white p-5 transition hover:-translate-y-1 hover:border-blue-primary hover:shadow-lg"><span className="text-2xl">{icon}</span><h3 className="mt-4 text-base font-bold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-ink2">{copy}</p></article></Reveal>)}</div></div></section>
    <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><Eyebrow>Built for Nigerian traders</Eyebrow><Heading>If you sell it, Cardinal OS runs it.</Heading></Reveal><Reveal className="mt-10"><div className="grid gap-3 grid-cols-2 md:grid-cols-4">{industries.map((item) => <div key={item} className="rounded-lg border border-blue-border bg-blue-pale px-4 py-4 text-sm font-bold text-ink">{item}</div>)}</div><div className="mt-7 rounded-xl bg-blue-primary px-6 py-6 text-base font-semibold leading-7 text-white">Trusted by traders at Alaba International Market, Lagos Trade Fair Complex, and markets across Lagos.</div></Reveal></div></section>
    <section className="bg-blue-pale py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><Eyebrow>Get started in minutes</Eyebrow><Heading>From signup to first order in under 10 minutes.</Heading></Reveal><div className="mt-10 grid gap-6 md:grid-cols-3">{[["01", "Sign Up Free", "Create your account, enter your business name and type. No credit card needed. Your 14-day free trial starts immediately."], ["02", "Add Your Products", "Add your products and prices in minutes. Import from CSV or add one by one."], ["03", "Start Taking Orders", "Record orders from any channel. Track payments. Dispatch with confidence."]].map(([number, title, copy]) => <Reveal key={number}><div className="border-l-2 border-blue-primary pl-5"><p className="font-mono text-xs font-bold text-blue-primary">{number}</p><h3 className="mt-3 font-display text-2xl font-bold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-ink2">{copy}</p></div></Reveal>)}</div></div></section>
    <section className="bg-blue-light py-20 sm:py-24"><div className="mx-auto max-w-3xl px-5 text-center sm:px-8"><Reveal>{/* TESTIMONIAL PLACEHOLDER - replace with real testimonial when received */}<p className="font-display text-3xl font-bold leading-tight text-ink sm:text-4xl">“We went from managing 6 WhatsApp groups to one platform. Every order, every payment, every delivery - in one place.”</p><p className="mt-6 font-mono text-xs font-bold uppercase tracking-[0.12em] text-blue-primary">Lagos Trader, Alaba International Market</p></Reveal></div></section>
    <section id="pricing" className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><Eyebrow>Simple, transparent pricing</Eyebrow><Heading>Start free. Grow as you go.</Heading><p className="mt-4 text-base text-ink2">All plans include a 14-day free trial. No credit card required.</p></Reveal><Reveal className="mt-10"><PricingCards /></Reveal><p className="mt-8 text-center text-sm text-ink2">Need something custom? <a href="mailto:hello@stuartdavidson.org?subject=Cardinal%20OS%20Enterprise%20Enquiry" className="font-bold text-blue-primary hover:underline">Talk to us about Cardinal OS Enterprise</a></p></div></section>
    <section className="py-20 sm:py-24"><div className="mx-auto max-w-3xl px-5 sm:px-8"><Reveal><Eyebrow>Questions?</Eyebrow><Heading>Everything you need to know.</Heading></Reveal><div className="mt-10 divide-y divide-blue-border border-y border-blue-border">{faqs.map(([question, answer], index) => <div key={question}><button type="button" onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-4 py-5 text-left font-bold text-ink"><span>{question}</span>{openFaq === index ? <ChevronUp size={19} className="shrink-0 text-blue-primary" /> : <ChevronDown size={19} className="shrink-0 text-blue-primary" />}</button>{openFaq === index && <p className="pb-5 text-sm leading-6 text-ink2">{answer}</p>}</div>)}</div></div></section>
    <section className="bg-blue-primary py-20 text-center text-white sm:py-24"><Reveal><div className="mx-auto max-w-2xl px-5 sm:px-8"><h2 className="font-display text-4xl font-bold leading-tight sm:text-5xl">Your business deserves better systems.</h2><p className="mt-5 text-base leading-7 text-blue-light">Join traders across Lagos who have replaced their WhatsApp chaos with one intelligent platform.</p><Link href="/signup" className="mt-8 inline-flex min-h-12 items-center justify-center rounded-lg bg-white px-6 text-sm font-bold text-blue-dark shadow-sm transition hover:bg-blue-light">Start Your Free Trial</Link><p className="mt-4 font-mono text-[10px] font-bold uppercase tracking-[0.1em] text-blue-light">14 days free · No credit card · Cancel anytime</p></div></Reveal></section>
  </>;
}
